### PR TITLE
Error code fixes

### PR DESCRIPTION
**Pull request by Resike**

### CODE REVIEW

**Comment by kaste** [comment]
Can you post some typical output of lua check, please?

**Comment by Resike** [comment]
SublimeLinter 4 has an function to show error/warning codes, without this fix the output is only `W`:
image

**Comment by kaste** [comment]
Ah that's cool, does it work for errors as well. 

Can you still post the raw output from the linter.

**Comment by Resike** [comment]
Raw print from python, also put some errors to it:
sublime_text_2018-03-19_23-10-52

**Comment by kaste** [comment]
Sorry I don't get this regex: Shouldn't it be 

`^.+:(?P<line>\d+):(?P<col>\d+)\-(?P<col_end>\d+): \((?:(?P<error>E\d+)|(?P<warning>W\d+))\) (?P<message>.+)`

That is, both error and warning (named) group match `\d+`



https://regex101.com/r/JFyiaZ/1

**Comment by Resike** [comment]
Yeah sorry I left the warning one out.

**Comment by kaste** [comment]
Okay, let's go.

**Comment by kaste** [comment]
🎉 

Released as https://github.com/SublimeLinter/SublimeLinter-luacheck/releases/tag/2.1.1

**Pull request merged**
